# Generated by Django 4.2 on 2026-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "journal",
            "0002_submission_assigned_editor_submission_decision_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialboardmember",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for board member",
                null=True,
                upload_to="board/",
            ),
        ),
    ]
