# Generated by Django 4.2 on 2026-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
